name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest pylint-odoo || true

      - name: Lint with pylint
        run: |
          pylint --load-plugins=pylint_odoo src/ controllers/ tools/ server.py || pylint src/ controllers/ tools/ server.py

      - name: Run smoke tests
        env:
          ODOO_API_KEY: dummy
          ODOO_URL: https://dummy-odoo-url.com/
          ODOO_DB: dummydb
          EXTRACT_ACCOUNT_TOKEN: dummy
        run: |
          pytest test_smoke.py || python3 test_smoke.py
